const Q=window.QUESTION_BANK||[];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const departments=[...new Set(Q.map(q=>q.department))];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const state={view:'home',mode:'顺序刷题',session:[],index:0,selected:new Set(),answered:false,started:Date.now(),quickTimer:null,stats:load('desk-stats',{}),settings:load('desk-settings',{theme:'lime',font:'system',scale:1,sound:true,soundPack:'木鱼',particles:true,quickSeconds:8}),last:load('desk-last',null)};
const modes=[
 ['顺序刷题','依题库原序稳步推进','⇥'],['组卷刷题','按题型比例随机成卷','▤'],['按部门刷题','聚焦指定业务部门','⌂'],['遗忘曲线','优先复习到期与薄弱题','◔'],
 ['循环模式','范围内循环，掌握后毕业','∞'],['背题模式','题目与答案同步阅读','◐'],['快答模式','倒计时揭晓并自动前进','↯'],['乱序模式','打散位置记忆与顺序依赖','⤨']
];
const eggs=[
 ['极限连击','连续答对，倍率随连胜上升'],['老板巡场','随机限时抽查，错一题即重来'],['盲盒三题','先选盒子，再揭晓三道题'],['电梯挑战','每层一题，答对才能上楼'],['番茄冲刺','25分钟专注答题，5分钟复盘'],['反向审题','先看答案，再找出对应题干'],['消消乐','连续掌握同部门三题即可消除'],['生存模式','三颗心，错题会扣除生命'],['银河远征','答对为飞船补充跃迁能量'],['错题复仇','只刷曾经击败过你的题'],
 ['五十连斩','50题连续挑战，中途不结算'],['两分钟雨','120秒内尽可能多答题'],['知识拼图','答对后逐块点亮今日图案'],['真假闪电','判断题专场，追求反应速度'],['选项猎人','只看选项，判断正确组合'],['同桌对战','同设备轮流答题，比拼正确率'],['静默禅修','隐藏进度与统计，只留题目'],['幸运数字','用幸运数字生成今日题单'],['弱点雷达','集中攻击正确率最低的部门'],['昨日重现','复刷昨天答错与犹豫过的题']
];
const themes=[
 ['lime','纸墨青柠','#f4f4ef','#d9f238'],['gba','掌机绿屏','#9ca65b','#ebf49d'],['cyber','赛博霓虹','#090a12','#14f1d9'],['ink','宋纸水墨','#eeeae1','#c74335'],['glass','液态玻璃','#dcecff','#77d6ff'],['sakura','云端樱雨','#f4e9ec','#ff9db5'],
 ...['星露农场','新海晴空','深海蓝洞','月球基地','赤焰熔岩','午夜书房','北欧雪原','琥珀胶片','薄荷苏打','香芋奶油','铜版报纸','机械黄铜','热带雨林','沙漠日落','海盐泡沫','宇宙星尘','复古终端','黑胶唱片','彩窗教堂','和风榻榻米','莫奈睡莲','包豪斯','孟菲斯','故宫朱墙','敦煌飞天','青花瓷','竹林清露','雨夜东京','港风霓虹','瑞士网格','咖啡手账','冰川极光','珊瑚礁','火星荒原','蓝图工程','像素地牢','漫画网点','糖果乐园','铅笔素描','极简黑白','森林露营','天空之城','深紫星云','牛皮纸档案','实验室白','午夜蓝','金属钛','山茶暖红'].map((n,i)=>[`custom${i}`,n,`hsl(${(i*47)%360} 42% ${i%2?18:88}%)`,`hsl(${(i*47+80)%360} 78% 58%)`])
];
function rec(q){return state.stats[q.id]||{right:0,wrong:0,streak:0,next:0,mastery:0}}
function save(){localStorage.setItem('desk-stats',JSON.stringify(state.stats));localStorage.setItem('desk-settings',JSON.stringify(state.settings))}
function summary(){let attempted=0,right=0,wrong=0,mastered=0;Object.values(state.stats).forEach(s=>{attempted++;right+=s.right||0;wrong+=s.wrong||0;if((s.mastery||0)>=4)mastered++});return{attempted,right,wrong,mastered,accuracy:right+wrong?Math.round(right/(right+wrong)*100):0}}
function navigate(v){clearInterval(state.quickTimer);state.view=v;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();scrollTo({top:0,behavior:'smooth'})}
function head(title,kicker='书桌 / STUDY DESK'){return `<header class="topline"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1></div><div class="top-actions"><button class="ghost" data-view="settings">外观</button><button class="icon-btn" id="installBtn" title="安装到设备">＋ 安装</button></div></header>`}
function home(){const s=summary(),due=Q.filter(q=>rec(q).next&&rec(q).next<=Date.now()).length;return `${head('下午好，开始今天的练习。')}<section class="hero-grid"><div class="hero-card"><div class="eyebrow">TODAY · ${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</div><h2>把复杂的知识，<br><em>练成直觉。</em></h2><div class="hero-actions"><button class="primary" data-mode="遗忘曲线">复习今日 ${due||Math.min(20,Q.length)} 题</button><button class="ghost" data-view="practice">选择练习方式</button></div></div><div class="meter-card"><div class="ring" style="--p:${Math.round(s.mastered/Q.length*100)}"><div><b>${Math.round(s.mastered/Q.length*100)}%</b><small>总体掌握</small></div></div><div class="mini-stats"><div><b>${s.attempted}</b><small>已练</small></div><div><b>${s.accuracy}%</b><small>正确率</small></div><div><b>${s.mastered}</b><small>掌握</small></div></div></div></section><div class="section-head"><div><h2>换一种方式继续</h2><p>不同路径，训练不同的记忆线索</p></div></div><section class="mode-grid">${modes.slice(0,4).map(modeCard).join('')}</section><div class="streak"><div><div class="eyebrow">QUESTION BANK</div><b>${Q.length.toLocaleString()} 道题 · ${departments.length} 个部门 · 数据仅存本机</b></div><button class="primary" data-view="practice">查看全部模式</button></div>`}
function modeCard(m){return `<button class="mode-card" data-mode="${m[0]}"><span class="mode-icon">${m[2]}</span><h3>${m[0]}</h3><p>${m[1]}</p></button>`}
function practice(){return `${head('今天想怎么练？','题库 / PRACTICE')}<div class="setup-grid"><section class="panel"><h2>练习设置</h2><div class="form-grid"><div class="field full"><label>部门</label><select id="dept"><option value="all">全部部门（${Q.length}题）</option>${departments.map(d=>`<option>${esc(d)}</option>`).join('')}</select></div><div class="field"><label>起始题号</label><input id="from" type="number" value="1" min="1" max="${Q.length}"></div><div class="field"><label>结束题号</label><input id="to" type="number" value="${Math.min(50,Q.length)}" min="1" max="${Q.length}"></div><div class="field full"><label>题型</label><div class="segmented" id="types"><button class="active" data-type="all">全部</button><button data-type="单选">单选</button><button data-type="多选">多选</button><button data-type="判断">判断</button></div></div><div class="field"><label>题数</label><select id="count">${[10,20,30,50,100,200].map(n=>`<option>${n}</option>`).join('')}<option value="all">范围内全部</option></select></div><div class="field"><label>顺序</label><select id="order"><option value="normal">按题号</option><option value="random">随机乱序</option><option value="weak">薄弱优先</option></select></div></div><button class="primary start-big" id="start">开始 · ${state.mode}</button></section><aside class="panel"><h3>刷题方式</h3><div class="mode-list">${modes.map(m=>`<button class="${state.mode===m[0]?'active':''}" data-pick-mode="${m[0]}"><b>${m[2]}　${m[0]}</b><small>${m[1]}</small></button>`).join('')}</div></aside></div>`}
function startSession(){const dept=$('#dept').value,type=$('#types .active').dataset.type,from=+$('#from').value||1,to=+$('#to').value||Q.length,count=$('#count').value,order=$('#order').value;let pool=Q.filter(q=>(dept==='all'||q.department===dept)&&(type==='all'||q.type===type)&&q.id>=Math.min(from,to)&&q.id<=Math.max(from,to));if(state.mode==='遗忘曲线')pool.sort((a,b)=>(rec(a).next||0)-(rec(b).next||0)||rec(a).mastery-rec(b).mastery);if(state.mode==='错题复仇')pool=pool.filter(q=>rec(q).wrong);if(order==='random'||state.mode==='乱序'||state.mode==='组卷刷题'||state.mode==='快答模式')pool=shuffle(pool);if(order==='weak')pool.sort((a,b)=>rec(a).mastery-rec(b).mastery);state.session=count==='all'?pool:pool.slice(0,+count);state.index=0;state.selected=new Set();state.answered=false;state.started=Date.now();if(!state.session.length){alert('当前条件下没有题目');return}navigate('quiz')}
function quiz(){const q=state.session[state.index];if(!q)return finish();const r=rec(q),progress=Math.round((state.index+1)/state.session.length*100);const reveal=state.answered||state.mode==='背题模式';return `${head(`${state.mode}`,'答题中 / FOCUS')}<div class="quiz-layout"><article class="quiz-card"><div class="quiz-meta"><span>${esc(q.department)} · ${q.type}</span><span><b>${state.index+1}</b> / ${state.session.length}　原题号 ${q.id}</span></div><div class="progress-line"><i style="width:${progress}%"></i></div><h2 class="question-stem">${esc(q.stem)}</h2><div class="options">${q.options.map(o=>`<button class="option ${state.selected.has(o.key)?'selected':''} ${reveal&&q.answer.includes(o.key)?'correct':''} ${state.answered&&state.selected.has(o.key)&&!q.answer.includes(o.key)?'wrong':''}" data-option="${o.key}"><span class="key">${o.key}</span><span>${esc(o.text)}</span></button>`).join('')}</div>${reveal?`<div class="answer-note"><b>答案 ${q.answer}</b> · 本题累计答对 ${r.right} 次，答错 ${r.wrong} 次</div>`:''}<div class="quiz-actions"><button class="ghost" id="paletteBtn">答题卡</button><div><button class="ghost" id="skip">稍后再做</button> <button class="primary" id="submit">${state.answered?'下一题':q.type==='多选'?'确认答案':'提交'}</button></div></div></article><aside class="quiz-side"><div class="timer-card"><small>${state.mode==='快答模式'?'本题倒计时':'本轮用时'}</small><b id="timer">00:00</b><span>${state.mode==='循环模式'?'掌握后将从循环中毕业':'保持专注，不追求无意义的速度'}</span></div><div class="panel"><h3>本轮答题卡</h3><div class="palette-mini">${state.session.slice(0,50).map((x,i)=>`<button data-jump="${i}" class="${i===state.index?'current':''} ${rec(x).session==='right'?'done':''} ${rec(x).session==='wrong'?'bad':''}">${i+1}</button>`).join('')}</div>${state.session.length>50?`<button class="ghost" id="paletteBtn2" style="width:100%;margin-top:12px">查看全部 ${state.session.length} 题</button>`:''}</div></aside></div>`}
function answer(force=false){const q=state.session[state.index];if(state.answered){next();return}if(!state.selected.size&&!force)return;const chosen=[...state.selected].sort().join(''),ok=chosen===q.answer;const r=state.stats[q.id]||{right:0,wrong:0,streak:0,mastery:0,next:0};if(ok){r.right++;r.streak++;r.mastery=Math.min(5,(r.mastery||0)+1);r.session='right'}else{r.wrong++;r.streak=0;r.mastery=Math.max(0,(r.mastery||0)-1);r.session='wrong'}const gaps=[0,10*60e3,24*3600e3,3*86400e3,7*86400e3,21*86400e3];r.next=Date.now()+gaps[r.mastery];state.stats[q.id]=r;state.answered=true;playSound(ok);save();render();if(state.mode==='快答模式')setTimeout(next,1200)}
function next(){clearInterval(state.quickTimer);state.index++;state.selected=new Set();state.answered=false;if(state.mode==='循环模式'&&state.index>=state.session.length){state.session=state.session.filter(q=>rec(q).mastery<4);state.index=0;if(state.session.length)state.session=shuffle(state.session)}if(state.index>=state.session.length)finish();else render()}
function finish(){const done=state.session,good=done.filter(q=>rec(q).session==='right').length;state.last={count:done.length,good,date:Date.now()};localStorage.setItem('desk-last',JSON.stringify(state.last));state.view='result';render()}
function result(){const l=state.last||{count:0,good:0};return `${head('这一轮，完成。','练习结算 / COMPLETE')}<section class="hero-grid"><div class="hero-card"><div class="eyebrow">SESSION COMPLETE</div><h2><em>${l.good}</em> / ${l.count}<br>正确作答</h2><div class="hero-actions"><button class="primary" data-view="practice">再来一组</button><button class="ghost" data-view="mistakes">复盘错题</button></div></div><div class="meter-card"><div class="ring" style="--p:${l.count?Math.round(l.good/l.count*100):0}"><div><b>${l.count?Math.round(l.good/l.count*100):0}%</b><small>本轮正确率</small></div></div><p style="text-align:center;color:var(--muted)">答案反馈已经安静地记录在题目本身，没有弹窗打断。</p></div></section>`}
function flash(){if(!state.session.length)state.session=shuffle(Q).slice(0,30),state.index=0;const q=state.session[state.index%state.session.length];return `${head('闪卡记忆','记忆 / FLASHCARDS')}<div class="flashcard" id="flashcard"><div class="flash-inner"><div class="flash-face"><div class="eyebrow">${esc(q.department)} · ${q.type}</div><p>${esc(q.stem)}</p><small>点击翻面</small></div><div class="flash-face flash-back"><div class="eyebrow">ANSWER</div><strong>${q.answer}</strong><p>${q.options.filter(o=>q.answer.includes(o.key)).map(o=>esc(o.text)).join('<br>')}</p></div></div></div><div class="flash-controls"><button class="ghost" data-flash="again">还不熟</button><button class="primary" data-flash="know">记住了</button></div>`}
function mistakes(){const qs=Q.filter(q=>rec(q).wrong).sort((a,b)=>rec(b).wrong-rec(a).wrong);return `${head('错题集','复盘 / MISTAKES')}<section class="panel"><div class="section-head" style="margin-top:0"><div><h2>${qs.length} 道待复盘</h2><p>按累计错误次数排序</p></div>${qs.length?'<button class="primary" id="mistakeStart">开始复仇</button>':''}</div>${qs.length?`<div class="bar-chart">${qs.slice(0,30).map(q=>`<div class="bar-row"><span>#${q.id}</span><div class="bar-track"><i style="width:${Math.min(100,rec(q).wrong*20)}%"></i></div><span>${rec(q).wrong} 错</span></div>`).join('')}</div>`:'<div class="empty">还没有错题。第一次练习后，这里会自动整理。</div>'}</section>`}
function statsView(){const s=summary(),dept=departments.map(d=>{const arr=Q.filter(q=>q.department===d),attempt=arr.filter(q=>state.stats[q.id]),avg=attempt.length?Math.round(attempt.reduce((n,q)=>{const r=rec(q);return n+r.right/(r.right+r.wrong)*100},0)/attempt.length):0;return[d,avg,attempt.length,arr.length]});return `${head('你的学习进度','数据 / PROGRESS')}<div class="card-grid"><div class="stat-card"><small>已接触题目</small><b>${s.attempted}</b><span>占题库 ${Math.round(s.attempted/Q.length*100)}%</span></div><div class="stat-card"><small>累计正确率</small><b>${s.accuracy}%</b><span>${s.right} 对 · ${s.wrong} 错</span></div><div class="stat-card"><small>完全掌握</small><b>${s.mastered}</b><span>连续记忆强度 ≥ 4</span></div></div><section class="panel" style="margin-top:18px"><h2>部门能力雷达</h2><div class="bar-chart">${dept.map(d=>`<div class="bar-row"><span title="${esc(d[0])}">${esc(d[0].slice(0,6))}</span><div class="bar-track"><i style="width:${d[1]}%"></i></div><span>${d[1]}%</span></div>`).join('')}</div></section>`}
function easter(){return `${head('20 种彩蛋模式','实验室 / PLAYGROUND')}<p style="color:var(--muted);margin-top:-15px;margin-bottom:24px">用规则变化制造新鲜感。选择一个模式即可基于当前题库开局。</p><div class="easter-grid">${eggs.map((e,i)=>`<button class="easter-card" data-egg="${e[0]}"><span class="mode-icon">${['✦','◆','◈','△','◎'][i%5]}</span><b>${e[0]}</b><p>${e[1]}</p></button>`).join('')}</div>`}
function settings(){return `${head('偏好设置','外观与声音 / PERSONALIZE')}<section class="panel settings-section"><h2>阅读</h2><div class="form-grid"><div class="field"><label>字体</label><select id="font"><option value="system">系统黑体</option><option value="serif">思源宋体 / 宋体</option><option value="kai">楷体</option><option value="mono">等宽字体</option><option value="rounded">圆体</option></select></div><div class="field"><label>字号</label><input id="scale" type="range" min="0.9" max="1.25" step="0.05" value="${state.settings.scale}"></div><div class="field"><label>自定义主色</label><input id="accent" type="color" value="#d9f238"></div><div class="field"><label>亮度</label><input id="brightness" type="range" min="70" max="115" value="100"></div><div class="field full"><label>自定义背景图（只保存在当前设备）</label><label class="upload">选择图片<input id="bgUpload" type="file" accept="image/*" hidden></label></div></div></section><section class="panel settings-section"><h2>声音与动效</h2><div class="form-grid"><div class="field"><label>答题音效</label><select id="soundPack"><option>木鱼</option><option>玻璃</option><option>街机</option><option>纸张</option><option>无声</option></select></div><div class="field"><label>粒子特效</label><select id="particlesOn"><option value="yes">开启</option><option value="no">关闭</option></select></div><div class="field"><label>快答倒计时（秒）</label><input id="quickSeconds" type="number" min="2" max="60" value="${state.settings.quickSeconds}"></div></div></section><section class="panel"><div class="section-head" style="margin-top:0"><div><h2>主题皮肤</h2><p>${themes.length} 种主题，每种都有对应色彩与粒子</p></div></div><div class="theme-grid">${themes.map(t=>`<button class="theme-card ${state.settings.theme===t[0]?'active':''}" data-theme-pick="${t[0]}" style="--p1:${t[2]};--p2:${t[3]}"><div class="theme-preview"></div><b>${t[1]}</b><small>${t[0].startsWith('custom')?'专属配色 · 动态粒子':'专属材质 · 动态粒子'}</small></button>`).join('')}</div></section>`}
function render(){const main=$('#main');main.innerHTML=({home,practice,quiz,result,flash,mistakes,stats:statsView,easter,settings}[state.view]||home)();bind();if(state.view==='quiz')tick()}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;navigate('practice')});$$('[data-pick-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.pickMode;render()});$$('#types button').forEach(b=>b.onclick=()=>{$$('#types button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});if($('#start'))$('#start').onclick=startSession;$$('[data-option]').forEach(b=>b.onclick=()=>selectOption(b.dataset.option));if($('#submit'))$('#submit').onclick=answer;if($('#skip'))$('#skip').onclick=next;$$('[data-jump]').forEach(b=>b.onclick=()=>{state.index=+b.dataset.jump;state.selected=new Set();state.answered=false;render()});['#paletteBtn','#paletteBtn2'].forEach(id=>{if($(id))$(id).onclick=showPalette});if($('#flashcard'))$('#flashcard').onclick=()=>$('#flashcard').classList.toggle('flipped');$$('[data-flash]').forEach(b=>b.onclick=()=>{if(b.dataset.flash==='know'){const q=state.session[state.index];const r=state.stats[q.id]||{right:0,wrong:0,mastery:0};r.mastery=Math.min(5,r.mastery+1);state.stats[q.id]=r;save()}state.index=(state.index+1)%state.session.length;render()});if($('#mistakeStart'))$('#mistakeStart').onclick=()=>{state.mode='错题复仇';state.session=shuffle(Q.filter(q=>rec(q).wrong));state.index=0;state.selected=new Set();state.answered=false;navigate('quiz')};$$('[data-egg]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.egg;state.session=shuffle(Q).slice(0,b.dataset.egg==='五十连斩'?50:20);state.index=0;state.selected=new Set();state.answered=false;navigate('quiz')});bindSettings();if($('#installBtn'))$('#installBtn').onclick=installApp}
function selectOption(k){if(state.answered)return;const q=state.session[state.index];if(q.type==='多选'){state.selected.has(k)?state.selected.delete(k):state.selected.add(k);render()}else{state.selected=new Set([k]);answer()}}
function showPalette(){const d=$('#sheet'),c=$('#sheetContent');c.innerHTML=`<div class="sheet-head"><h2>答题卡 · ${state.session.length}题</h2><button class="close">×</button></div><div class="palette-mini">${state.session.map((q,i)=>`<button data-sheet-jump="${i}" class="${i===state.index?'current':''} ${rec(q).session==='right'?'done':''} ${rec(q).session==='wrong'?'bad':''}">${i+1}</button>`).join('')}</div>`;$('.close',c).onclick=()=>d.close();$$('[data-sheet-jump]',c).forEach(b=>b.onclick=()=>{state.index=+b.dataset.sheetJump;state.selected=new Set();state.answered=false;d.close();render()});d.showModal()}
function tick(){clearInterval(state.quickTimer);const start=Date.now();const limit=state.settings.quickSeconds*1000;state.quickTimer=setInterval(()=>{const el=$('#timer');if(!el)return clearInterval(state.quickTimer);if(state.mode==='快答模式'){const left=Math.max(0,limit-(Date.now()-start));el.textContent=(left/1000).toFixed(1);if(left<=0){clearInterval(state.quickTimer);if(!state.answered){state.selected=new Set();answer(true)}}}else{const sec=Math.floor((Date.now()-state.started)/1000);el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}},100)}
function bindSettings(){if($('#font')){$('#font').value=state.settings.font;$('#font').onchange=e=>{state.settings.font=e.target.value;applySettings();save()};$('#scale').oninput=e=>{state.settings.scale=+e.target.value;applySettings();save()};$('#accent').oninput=e=>document.documentElement.style.setProperty('--accent',e.target.value);$('#brightness').oninput=e=>document.body.style.filter=`brightness(${e.target.value}%)`;$('#soundPack').value=state.settings.soundPack;$('#soundPack').onchange=e=>{state.settings.soundPack=e.target.value;save()};$('#particlesOn').value=state.settings.particles?'yes':'no';$('#particlesOn').onchange=e=>{state.settings.particles=e.target.value==='yes';save();particleLoop()};$('#quickSeconds').onchange=e=>{state.settings.quickSeconds=Math.max(2,+e.target.value);save()};$('#bgUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{localStorage.setItem('desk-bg',rd.result);applySettings()};rd.readAsDataURL(f)}}$$('[data-theme-pick]').forEach(b=>b.onclick=()=>{state.settings.theme=b.dataset.themePick;applySettings();save();render()})}
function applySettings(){const t=themes.find(x=>x[0]===state.settings.theme)||themes[0];document.body.dataset.theme=['cyber','gba','ink','glass','sakura'].includes(t[0])?t[0]:'';if(t[0].startsWith('custom')){document.documentElement.style.setProperty('--bg',t[2]);document.documentElement.style.setProperty('--accent',t[3]);document.documentElement.style.setProperty('--surface','color-mix(in srgb, var(--bg) 82%, white)')}else{document.documentElement.style.removeProperty('--bg');document.documentElement.style.removeProperty('--accent');document.documentElement.style.removeProperty('--surface')}const fonts={system:'"Microsoft YaHei","PingFang SC",system-ui,sans-serif',serif:'"Noto Serif SC",SimSun,serif',kai:'STKaiti,KaiTi,serif',mono:'ui-monospace,"Cascadia Mono",monospace',rounded:'"Arial Rounded MT Bold","Microsoft YaHei",sans-serif'};document.documentElement.style.setProperty('--font',fonts[state.settings.font]||fonts.system);document.documentElement.style.setProperty('--scale',state.settings.scale);const bg=localStorage.getItem('desk-bg');document.documentElement.style.setProperty('--bg-image',bg?`linear-gradient(color-mix(in srgb,var(--bg) 82%,transparent),color-mix(in srgb,var(--bg) 82%,transparent)),url("${bg}")`:'none');$('#themeName')&&($('#themeName').textContent=t[1]);particleLoop()}
function playSound(ok){if(state.settings.soundPack==='无声')return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);const bases={木鱼:[ok?620:190,'sine'],玻璃:[ok?980:260,'sine'],街机:[ok?760:140,'square'],纸张:[ok?420:210,'triangle']};const [f,type]=bases[state.settings.soundPack]||bases['木鱼'];o.type=type;o.frequency.setValueAtTime(f,a.currentTime);o.frequency.exponentialRampToValueAtTime(ok?f*1.4:f*.7,a.currentTime+.15);g.gain.setValueAtTime(.07,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.18);o.start();o.stop(a.currentTime+.18)}
let pRun=0;function particleLoop(){pRun++;const run=pRun,c=$('#particles'),x=c.getContext('2d');if(!state.settings.particles){x.clearRect(0,0,c.width,c.height);return}const t=themes.find(a=>a[0]===state.settings.theme)||themes[0],seed=[...t[0]].reduce((n,ch)=>n+ch.charCodeAt(0),0);c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);const ps=Array.from({length:22},(_,i)=>({x:(i*97+seed)%innerWidth,y:(i*53+seed)%innerHeight,r:1+(i%4),v:.08+(i%5)*.035}));function frame(){if(run!==pRun)return;x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle=t[3]+'44';ps.forEach((p,i)=>{p.y-=p.v;if(p.y<-8)p.y=innerHeight+8;x.beginPath();if(t[0]==='gba')x.rect(p.x,p.y,p.r*2,p.r*2);else{x.arc(p.x+Math.sin(p.y/80+i)*8,p.y,p.r,0,7)}x.fill()});requestAnimationFrame(frame)}frame()}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
let deferred;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});async function installApp(){if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else alert('在浏览器菜单中选择“安装应用”或“添加到主屏幕”即可。')}
$$('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#themeQuick').onclick=()=>navigate('settings');applySettings();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
